from telegram import Update, ChatMember
from telegram.ext import ContextTypes
from telegram.constants import ChatType
from bot import bot, logger
from bot.helper.telegram_helpers.telegram_helper import Message
from bot.functions.group_management.pm_error import _pm_error
from bot.functions.group_management.log_channel import _log_channel
from bot.functions.del_command import func_del_command
from bot.functions.group_management.check_permission import _check_permission


async def func_invite_link(update: Update, context: ContextTypes.DEFAULT_TYPE):
    chat = update.effective_chat
    user = update.effective_user

    if chat.type == ChatType.PRIVATE:
        await _pm_error(chat.id)
        return

    await func_del_command(update, context)

    if user.is_bot:
        await Message.reply_message(update, "I don't take permission from anonymous admins!")
        return
    
    sent_msg = await Message.reply_message(update, "💭")
    _chk_per = await _check_permission(update, user=user)
    if not _chk_per:
        await Message.edit_message(update, "Oops! Please try again or report the issue.", sent_msg)
        return
    
    if _chk_per["bot_permission"].status != ChatMember.ADMINISTRATOR:
        await Message.edit_message(update, "I'm not an admin in this chat!", sent_msg)
        return
    
    if _chk_per["user_permission"].status not in [ChatMember.ADMINISTRATOR, ChatMember.OWNER]:
        await Message.edit_message(update, "You aren't an admin in this chat!", sent_msg)
        return

    if _chk_per["user_permission"].status == ChatMember.ADMINISTRATOR:
        if not _chk_per["user_permission"].can_invite_users:
            await Message.edit_message(update, "You don't have enough rights to invite users in this chat!", sent_msg)
            return
    
    if not _chk_per["bot_permission"].can_invite_users:
        await Message.edit_message(update, "I don't have enough rights to invite users in this chat!", sent_msg)
        return
    
    try:
        invite_link = await bot.create_chat_invite_link(chat.id, name=user.first_name)
    except Exception as e:
        logger.error(e)
        await Message.edit_message(update, str(e), sent_msg)
        return
    
    msg = (
        f"<b>Private invite link:</b> {invite_link.invite_link}\n"
        f"<b>Generated by:</b> {user.first_name}"
    )

    if chat.link:
        msg = (
            f"<b>Public invite link:</b> {chat.link}\n{msg}"
        )
    
    await Message.edit_message(update, msg, sent_msg)
    await _log_channel(update, chat, user, action="INVITE")
